### ISSUE TITLE
MPI Framework improvements

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#274]
Update and improve the MPI framework simplifying and making more robust.

https://github.com/pace-neutrons/Herbert/issues/159

**Comment by abuts** [comment]
fixed by Herbert [#190](https://github.com/pace-neutrons/Herbert/issues/190); [#188](https://github.com/pace-neutrons/Herbert/issues/188) [#186](https://github.com/pace-neutrons/Herbert/issues/186); [#184](https://github.com/pace-neutrons/Herbert/issues/184) and [#159](https://github.com/pace-neutrons/Herbert/issues/159)
