### ISSUE TITLE
Create ADR recording Python/Matlab API discussions

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#575]
Create a new ADR documenting the decisions arising from the Python/MATLAB API meeting:

- support automated `kwarg`->`'key', value` mapping in Python to MATLAB calls
- require flag arguments to have `-` prefix
- throw error if flag and keyword argument are both defined and do not agree
- for all MATLAB flag arguments, support an additional keyword argument of the same name (without the `-` prefix) to support Python and retain support for flags in MATLAB
- remove MATLAB APIs where the number of arguments defines the argument list by defining new functions or new keyword arguments:
-- `cut(..., [proj], ...)` becomes `cut_with_default_projection(...)` and `cut(..., proj, ...)`, 
-- `dispersion_plot([lattice], ...)` becomes `dispersion_plot(..., 'lattice', lattice_params)`

**Comment by mducle** [comment]
For the final item, I would suggest `recut` or `cut_within` instead of `cut_with_default_projection`.

In addition, there is also the case of `disp2sqw`, which I would suggest be split into `disp2sqw_hkl`, `disp2sqw_q` and `disp2sqw_qe` for the `nargin`=7, 5 and 4 cases respectively with a gateway function `disp2sqw` retained which just checks the number of input arguments and prints a "deprecated" message and then dispatches to the relevant function.
