### ISSUE TITLE
signal should use unary operation manager and work on filebased data

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#889]
Currently signal function works in memory only. In fact it is very similar to other unary operations so should use operation manager and work similarly to other unit operations on filebased data too.

**Comment by oerc0122** [comment]
Determined usage: 
- Set `sqw.pix` `signal` `variance` to arbitrary coordinates for debugging purposes or for applying transformations based on coordinates
- Can rework into `unary_op_manager` requires making `coordinates_calc_` return `struct` 
- Doable since `coordinates_calc_` only used in `signal`
- Need advice on priority
